### PR TITLE
Improved javadoc

### PR DESCRIPTION
**Pull request by SackCastellon**
Improved Javadoc by adding HTML tables so when viewing the documentation, in IntelliJ for example, you see this:

image

Instead of the previous version which showed this:

image

### CODE REVIEW

**Comment by soc** [comment]
@SackCastellon Wow, this is nice, thank you!

Could you try rebasing this PR? Github is complaining about some conflicts...

**Comment by SackCastellon** [comment]
I've tried to rebase a few times but I am not sure if I did it right.

**Comment by soc** [comment]
Did you pull the recent changes before rebasing? I assume that you are based on a commit before I released version 9 ...

**Comment by SackCastellon** [comment]
I forked on version 8 and then I updated when you released version 9.
But I think I finally figured it out

**Comment by soc** [comment]
@SackCastellon Thanks a lot, I merged your changes in https://github.com/soc/directories-jvm/commit/072bef287b0b75a9e49c7f64b40a10e6d2edf908!

**Pull request closed without merging**
